name: Testing

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  test:
    name: Cucumber and Rspec Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Set up Ruby 3.3.8
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.3.8
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Cucumber
        run: bundle exec cucumber
      - name: Rspec
        run: bundle exec rspec